apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-gateway
  name: {{lower .username}}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: "4180"
    port: 4180
  selector:
    app: user-gateway