{{- $root := . -}}
{{- range .Values.users }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{lower .}}-space
  name: {{lower .}}-space
  namespace: {{ $root.Release.Namespace | quote }}
spec:
  ports:
  - name: "29180"
    port: 29180
  - name: "29432"
    port: 29432
  - name: "29500"
    port: 29500
  - name: "11211"
    port: 11211
  - name: "9191"
    port: 9191
  selector:
    app: {{lower .}}-space
{{- end}}