{{if .Values.ingress.tls.createCertificate }}
{{- $root := . -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Namespace }}-cert
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: {{ .Values.ingress.secretName | quote }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
  - {{ .Values.ingress.host }}
  # {{- range .Values.users }}
  # - {{lower .username}}.{{ $root.Values.ingress.host }}
  # {{- end }}
  issuerRef:
    name: {{ .Values.ingress.tls.clusterIssuerName | quote }}
    kind: ClusterIssuer
{{- end }}