{{- $root := . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
  name: project-ingress
  namespace: {{ .Release.Namespace}}
spec: 
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    {{- range .Values.users }}
    - {{lower .username}}.{{ $root.Values.ingress.host }}
    {{- end }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: user-gateway
          servicePort: 4180
  {{- range .Values.users }}
  - host: {{lower .username}}.{{ $root.Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{lower .username}}-space
          servicePort: 29500
  {{- end }}