apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: airflow-webserver
