{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: memcache
  namespace: {{ $root.Release.Namespace | quote }}
spec:
  ports:
  - name: "11211"
    port: 11211
    targetPort: 11211
  selector:
    app: memcache
