{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
  namespace: {{ $root.Release.Namespace | quote }}
spec:
  ports:
  - name: airflow-postgres
    port: 5432
    targetPort: 5432
  selector:
    app: airflow-postgres
