apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{lower .username}}-registry-cfg
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: user-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: user-gateway
  template:
    metadata:
      labels:
        app: user-gateway
    spec:
      containers:  
      - name: nginx
        image: nginx
        env:
        - name: FORCE_RELOAD
          value: {{ randAlphaNum 16 | quote }}
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: 10Mi
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          name: user-gateway-cfg
      - name: oauth
        image: quay.io/pusher/oauth2_proxy:v6.1.1
        env:
        - name: OAUTH2_PROXY_PROVIDER
          value: {{ required "A valid .Values.oauth.proxyProvider entry required!" .Values.oauth.proxyProvider | quote }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: {{ required "A valid .Values.oauth.cookieSecret entry required!" .Values.oauth.cookieSecret | quote }}
        - name: OAUTH2_PROXY_CLIENT_ID
          value: {{ required "A valid .Values.oauth.clientId entry required!" .Values.oauth.clientId | quote }}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: {{ required "A valid .Values.oauth.clientSecret entry required!" .Values.oauth.clientSecret | quote }}
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: {{ required "A valid .Values.oauth.emailDomains entry required!" .Values.oauth.emailDomains | quote }}
        - name: OAUTH2_PROXY_GITHUB_ORG
          value: {{ required "A valid .Values.oauth.gitHubOrg entry required!" .Values.oauth.gitHubOrg | quote }}
        - name: OAUTH2_PROXY_UPSTREAMS
          value: http://localhost:80
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: :4180
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: {{ required "A valid .Values.oauth.redirectUrl entry required!" .Values.oauth.redirectUrl | quote }}
        - name: OAUTH2_PROXY_SKIP_AUTH_REGEX
          value: "{{- $local := dict "first" true -}} {{range .Values.users}} {{- if not $local.first -}},{{- end -}} {{lower .username}}//* {{- $_ := set $local "first" false -}} {{ end }}"
        resources:
          requests:
            memory: 10Mi
        ports:
        - containerPort: 4180
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8}}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8}}
      {{- end }}  
      volumes:
      - name: user-gateway-cfg
        configMap:
          name: user-gateway-cfg
          items:
            - key: default.conf
              path: default.conf