apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-space
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: shared-space
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: shared-space
  template:
    metadata:
      labels:
        app: shared-space
    spec:
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: controller
      automountServiceAccountToken: true
      containers:
      - name: mlflow
        image: {{ .Values.applications.mlflow.image }}
        command: ["mlflow", "server", "--host", "0.0.0.0", "--default-artifact-root", "ftp://admin:admin@shared-space", "--backend-store-uri", "sqlite:///mlflow.db"]
        volumeMounts:
          - mountPath: /home/engineer/mlflow/
            subPath: mlflow
            name: shared-disk
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      {{- if .Values.applications.controller.enabled }}
      - name: controller
        image: {{ .Values.applications.controller.image }}
        ports:
        - containerPort: 5002
        resources: {{- toYaml .Values.applications.controller.resources | nindent 10}}
        imagePullPolicy: Always
      {{- end }}
      - name: ftp-server
        image: stilliard/pure-ftpd
        env:
        - name: PUBLICHOST
          value: shared-space
        - name: FTP_USER_NAME
          value: admin
        - name: FTP_USER_PASS
          value: admin
        - name: FTP_USER_HOME
          value: /home/admin
        volumeMounts:
          - mountPath: /home/admin/
            subPath: ftp
            name: shared-disk
        ports:
        - containerPort: 21
        - containerPort: 30000
        - containerPort: 30001
        - containerPort: 30002
        - containerPort: 30003
        - containerPort: 30004
        - containerPort: 30005
        - containerPort: 30006
        - containerPort: 30007
        - containerPort: 30008
        - containerPort: 30009
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8}}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8}}
      {{- end }}
      volumes:
        - name: shared-disk
          persistentVolumeClaim:
            claimName: shared-disk