apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: disk
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 32Gi