apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-airflow
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: disk
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi