{{- $root := . -}}
{{- range .Values.users }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{lower .username}}-apps-html
  namespace: {{ $root.Release.Namespace | quote }}
data:
  # yamllint disable rule:line-length
  index.html: |
    <!DOCTYPE html>
    <head>
      <meta charset="UTF-8">
    </head>
    <body>
      <h2>Tools</h2>
      <ul>
        <li><a href="./code/">Code</a></li>
        <li><a href="./jupyter/">JupyterLab</a></li>
        <li><a href="./jupyter/tree">Jupyter (classic)</a></li>
        {{- if $root.Values.applications.rstudio.enabled }}
        <li><a href="./rstudio/">R-Studio</a></li>
        {{- end }}
        <li><a href="/">Controlador de Ambiente</a></li>
      </ul>
      <h2>Applications</h2>
      <ul>
        <li><a href="./airflow/">Airflow</a></li>
        <li><a href="/mlflow/">Mlflow</a></li>
      </ul>
      <h2>Other</h2>
      <ul>
        <li><a href="./browser/">Firefox</a></li>
      </ul>
      <h2>Instructions</h2>
      <h3>Mlflow</h3>
      <p>
        Tracking URI for cluster internal use: http://shared-space:5000
      </p>
      <h3>SSH (Experimental)</h3>
      <p>
        Download <a href="{{ $root.Values.ssh.clientDownloadLink }}">ws-tunnel</a> and execute: ws-tunnel wss://{{ $root.Values.ingress.host }}/{{lower .username}}/ssh
      </p>
      <p>
        Then connect to the port exposed: ssh {{lower .username}}@localhost -p EXPOSED_PORT
      </p>
      <script>
        function onLoad(){
          fetch("./password").then(function(response) {
            response.text().then(function(password){
              document.getElementById('password').value = password;
            })
          });
        }
    
        function copyToClipboard() {
          var copyText = document.getElementById("password");
          copyText.select();
          copyText.setSelectionRange(0, 99999);
          document.execCommand("copy");
        }
        onLoad();
      </script>
    </body>
{{- end }}