# Default values for dev-env-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

users:
  - username: raphael-bos
    # nodeSelector:
    #   key: value
  - username: guifneves

oauth:
  proxyProvider: github
  cookieSecret: someSecret
  clientId: someId
  clientSecret: someSecret
  emailDomains: '*'
  gitHubOrg: 'org'
  redirectUrl: https://dev.project.raizen.ai/oauth2/callback

applications:
  airflow:
    image: raizenanalyticsdev.azurecr.io/airflow-base
    tag: latest
  vscode:
    image: codercom/code-server
    args: ['code-server', '--auth', 'none', '--bind-addr', '0.0.0.0:29901', '.']
    resources:
      requests:
        memory: "512Mi"
        cpu: "450m"
  jupyter:
    image: raizenanalyticsdev.azurecr.io/code-server:latest
    args: ["jupyter", "lab", "--ip", "0.0.0.0", "--NotebookApp.token=''", "--NotebookApp.base_url=/home/jupyter", "--port", "29902"]
    resources:
      requests:
        memory: "512Mi"
        cpu: "450m"
  rstudio:
    enabled: true
    image: raizenanalyticsdev.azurecr.io/code-server:latest
    args: ["/usr/lib/rstudio-server/bin/rserver", "--server-daemonize=0", "--auth-none=1", "--www-root-path=/rstudio/"]
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
  controller:
    enabled: true
    image: raizenanalyticsdev.azurecr.io/environment-controller:main
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
  mlflow:
    image: raizenanalyticsdev.azurecr.io/mlflowz
  scheduleUserSpaceStop:
    enabled: true
    image: bitnami/kubectl:1.22
    cron: "0 23 * * *"
  registry:
    admin:
      enabled: false
      secret: admin-registry
      # secret must have username and password keys

ingress:
  host: dev.project.raizen.ai
  secretName: tls-ingress-secret
  tls:
    createCertificate: true
    clusterIssuerName: letsencrypt-prod # Retirar

ssh:
  clientDownloadLink: https://github.com/raizen-analytics/helm-charts/releases

imagePullSecrets:
  - name: acr-secret

# nodeSelector:
#   key: value2
  
# tolerations:
#   - key: "key"
#     operator: "Equal"
#     value: "value"
#     effect: "NoSchedule"

volumes:
  users:
    disk:
      size: 32Gi
      storageClassName: default
    file:
      size: 1Gi
      storageClassName: azurefile
  shared:
    disk:
      size: 32Gi
      storageClassName: default
    file:
      size: 1Gi
      storageClassName: azurefile